// nextjs-reevit/app/checkout/page.tsx
'use client'

import { useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { HugeiconsIcon } from '@hugeicons/react'
import { ArrowLeft02Icon, SecurityCheckIcon } from '@hugeicons/core-free-icons'
import { ReevitCheckout } from '@reevit/react'
import '@reevit/react/styles.css'
import { useCart } from '@/lib/cart'
import { formatPrice } from '@/lib/products'
import { toast } from '@/components/Toaster'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Separator } from '@/components/ui/separator'

const countries = [
  { code: 'GH', name: 'Ghana', currency: 'GHS' },
  { code: 'NG', name: 'Nigeria', currency: 'NGN' },
  { code: 'KE', name: 'Kenya', currency: 'KES' },
]

export default function CheckoutPage() {
  const router = useRouter()
  const { items, total, clearCart } = useCart()
  const [customerEmail, setCustomerEmail] = useState('')
  const [customerName, setCustomerName] = useState('')
  const [selectedCountry, setSelectedCountry] = useState('GH')

  const selectedCountryData = countries.find((c) => c.code === selectedCountry)
  const publicKey = process.env.NEXT_PUBLIC_REEVIT_PUBLIC_KEY || 'pk_test_demo'
  const apiBaseUrl = process.env.NEXT_PUBLIC_REEVIT_API_URL

  if (items.length === 0) {
    return (
      <div className="container mx-auto px-4 py-24 text-center">
        <div className="text-8xl mb-6">🛒</div>
        <h1 className="text-3xl font-bold mb-4">Your cart is empty</h1>
        <p className="text-muted-foreground mb-8">Add some products before checking out</p>
        <Link href="/">
          <Button size="lg">
            <HugeiconsIcon icon={ArrowLeft02Icon} className="mr-2 h-5 w-5" />
            Continue Shopping
          </Button>
        </Link>
      </div>
    )
  }

  const handlePaymentSuccess = (result: { reference?: string; id?: string }) => {
    toast.success('Payment successful!')
    clearCart()
    router.push(`/payment/${result.reference || result.id || 'unknown'}`)
  }

  const handlePaymentError = (error: { message?: string }) => {
    toast.error(error.message || 'Payment failed')
  }

  return (
    <div className="container mx-auto px-4 py-12">
      <div className="flex items-center gap-4 mb-8">
        <Link href="/cart">
          <Button variant="ghost" size="icon">
            <HugeiconsIcon icon={ArrowLeft02Icon} className="h-5 w-5" />
          </Button>
        </Link>
        <h1 className="text-3xl font-bold">Checkout</h1>
      </div>

      <div className="grid lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          {/* Customer Information */}
          <Card>
            <CardHeader>
              <CardTitle>Customer Information</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid sm:grid-cols-2 gap-4">
                <div>
                  <label className="text-sm font-medium text-muted-foreground mb-2 block">
                    Full Name
                  </label>
                  <Input
                    type="text"
                    value={customerName}
                    onChange={(e) => setCustomerName(e.target.value)}
                    placeholder="John Doe"
                  />
                </div>
                <div>
                  <label className="text-sm font-medium text-muted-foreground mb-2 block">
                    Email Address
                  </label>
                  <Input
                    type="email"
                    value={customerEmail}
                    onChange={(e) => setCustomerEmail(e.target.value)}
                    placeholder="john@example.com"
                  />
                </div>
              </div>
              <div>
                <label className="text-sm font-medium text-muted-foreground mb-2 block">
                  Country
                </label>
                <select
                  value={selectedCountry}
                  onChange={(e) => setSelectedCountry(e.target.value)}
                  className="w-full h-10 px-3 rounded-md border border-input bg-background text-sm"
                >
                  {countries.map((country) => (
                    <option key={country.code} value={country.code}>
                      {country.name} ({country.currency})
                    </option>
                  ))}
                </select>
              </div>
            </CardContent>
          </Card>

          {/* Security Notice */}
          <Card className="border-primary/20 bg-primary/5">
            <CardContent className="flex items-start gap-4 p-4">
              <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                <HugeiconsIcon icon={SecurityCheckIcon} className="h-5 w-5 text-primary" />
              </div>
              <div>
                <h3 className="font-semibold mb-1">Secure Checkout</h3>
                <p className="text-sm text-muted-foreground">
                  Your payment is securely processed through{' '}
                  <span className="text-primary font-medium">Reevit's</span> unified
                  payment platform. We automatically route to the best provider.
                </p>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Order Summary */}
        <div className="lg:sticky lg:top-24 h-fit">
          <Card>
            <CardHeader>
              <CardTitle>Order Summary</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Items */}
              <div className="space-y-3">
                {items.map((item) => (
                  <div key={item.product.id} className="flex items-center gap-3">
                    <img
                      src={item.product.image}
                      alt={item.product.name}
                      className="w-12 h-12 rounded-lg object-cover"
                    />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">
                        {item.product.name}
                      </p>
                      <p className="text-xs text-muted-foreground">Qty: {item.quantity}</p>
                    </div>
                    <span className="text-sm font-semibold">
                      {formatPrice(item.product.price * item.quantity)}
                    </span>
                  </div>
                ))}
              </div>

              <Separator />

              {/* Totals */}
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Subtotal</span>
                  <span>{formatPrice(total)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Shipping</span>
                  <span className="text-green-600 font-medium">Free</span>
                </div>
                <Separator />
                <div className="flex justify-between">
                  <span className="font-bold">Total</span>
                  <span className="text-xl font-bold text-primary">
                    {formatPrice(total, selectedCountryData?.currency)}
                  </span>
                </div>
              </div>

              {/* Reevit Checkout */}
              <ReevitCheckout
                publicKey={publicKey}
                amount={total}
                currency={selectedCountryData?.currency || 'GHS'}
                email={customerEmail}
                reference={`ORD-${Date.now()}`}
                metadata={{
                  customer_name: customerName,
                  order_items: items.map((i) => i.product.id).join(','),
                  // IMPORTANT: These values are required for webhook routing
                  // Get your org_id and connection_id from your Reevit dashboard
                  org_id: process.env.NEXT_PUBLIC_REEVIT_ORG_ID || "your-organization-id",
                  connection_id: process.env.NEXT_PUBLIC_REEVIT_CONNECTION_ID || "your-connection-id",
                  // payment_id is typically the order/invoice ID from your system
                  payment_id: `ORD-${Date.now()}`
                }}
                paymentMethods={['card', 'mobile_money']}
                onSuccess={handlePaymentSuccess}
                onError={handlePaymentError}
                theme={{
                  primaryColor: '#ea580c',
                  darkMode: false,
                }}
                apiBaseUrl={apiBaseUrl}
              >
                <Button className="w-full" size="lg">
                  Pay {formatPrice(total, selectedCountryData?.currency)}
                </Button>
              </ReevitCheckout>

              <p className="text-xs text-center text-muted-foreground">
                🔒 100% Encrypted & Secure
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

// svelte+reevit/src/routes/Checkout.svelte
<script lang="ts">
  import { ArrowLeft, ShieldCheck } from 'lucide-svelte'
  import { ReevitCheckout } from '@reevit/svelte'
  import { cart } from '$lib/cart.svelte'
  import { formatPrice } from '$lib/products'

  let customerEmail = $state('')
  let customerName = $state('')
  let selectedCountry = $state('GH')

  const countries = [
    { code: 'GH', name: 'Ghana', currency: 'GHS' },
    { code: 'NG', name: 'Nigeria', currency: 'NGN' },
    { code: 'KE', name: 'Kenya', currency: 'KES' },
  ]

  const selectedCountryData = $derived(countries.find((c) => c.code === selectedCountry))
  const publicKey = import.meta.env.VITE_REEVIT_PUBLIC_KEY || 'pk_test_demo'

  function handlePaymentSuccess(event: CustomEvent) {
    const result = event.detail
    cart.clearCart()
    window.location.hash = `/payment/${result.reference || result.id}`
  }

  function handlePaymentError(event: CustomEvent) {
    console.error('Payment failed:', event.detail)
  }
</script>

{#if cart.items.length === 0}
  <main class="container mx-auto px-6 py-24 text-center">
    <div class="text-6xl mb-6">🛒</div>
    <h1 class="text-3xl font-bold mb-4">Your cart is empty</h1>
    <p class="text-muted-foreground mb-8">Add some products before checking out</p>
    <a href="#/" class="btn btn-primary h-12 px-8 text-lg">
      <ArrowLeft class="w-5 h-5 mr-2" /> Continue Shopping
    </a>
  </main>
{:else}
  <main class="container mx-auto px-6 py-12">
    <div class="flex items-center gap-4 mb-12">
      <a href="#/cart" class="btn btn-ghost h-10 w-10 p-0">
        <ArrowLeft class="w-5 h-5" />
      </a>
      <h1 class="text-4xl font-bold">Checkout</h1>
    </div>

    <div class="grid lg:grid-cols-3 gap-12">
      <div class="lg:col-span-2 space-y-8">
        <section class="glass p-8 rounded-3xl">
          <h2 class="text-2xl font-bold mb-6">Customer Information</h2>
          <div class="grid sm:grid-cols-2 gap-6">
            <div>
              <label class="block text-sm font-bold text-muted-foreground mb-2">Full Name</label>
              <input bind:value={customerName} type="text" placeholder="John Doe" class="input" required />
            </div>
            <div>
              <label class="block text-sm font-bold text-muted-foreground mb-2">Email Address</label>
              <input bind:value={customerEmail} type="email" placeholder="john@example.com" class="input" required />
            </div>
          </div>
          <div class="mt-6">
            <label class="block text-sm font-bold text-muted-foreground mb-2">Country</label>
            <select bind:value={selectedCountry} class="input appearance-none cursor-pointer">
              {#each countries as country (country.code)}
                <option value={country.code} class="bg-background">{country.name} ({country.currency})</option>
              {/each}
            </select>
          </div>
        </section>

        <div class="glass p-6 rounded-2xl border border-accent/20 bg-accent/5">
          <div class="flex items-start gap-4">
            <div class="w-12 h-12 rounded-xl bg-accent/10 flex items-center justify-center shrink-0">
              <ShieldCheck class="w-6 h-6 text-accent" />
            </div>
            <div>
              <h3 class="text-lg font-bold mb-1">Secure Checkout</h3>
              <p class="text-sm text-muted-foreground">
                Your payment is securely processed through <span class="text-foreground font-semibold">Reevit's</span> unified payment platform.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="lg:sticky lg:top-24 h-fit">
        <div class="glass p-8 rounded-3xl">
          <h2 class="text-xl font-bold mb-6">Order Summary</h2>
          <div class="space-y-4 mb-6">
            {#each cart.items as item (item.product.id)}
              <div class="flex items-center gap-3">
                <div class="w-12 h-12 rounded-lg overflow-hidden shrink-0">
                  <img src={item.product.image} alt={item.product.name} class="w-full h-full object-cover" />
                </div>
                <div class="flex-1 min-w-0">
                  <p class="font-medium text-sm line-clamp-1">{item.product.name}</p>
                  <p class="text-xs text-muted-foreground">Qty: {item.quantity}</p>
                </div>
                <span class="font-bold text-sm">{formatPrice(item.product.price * item.quantity)}</span>
              </div>
            {/each}
          </div>
          <div class="h-px bg-border my-6"></div>
          <div class="space-y-3 mb-8">
            <div class="flex justify-between text-sm text-muted-foreground">
              <span>Subtotal</span>
              <span class="text-foreground">{formatPrice(cart.total)}</span>
            </div>
            <div class="flex justify-between text-sm text-muted-foreground">
              <span>Shipping</span>
              <span class="text-success font-bold">Free</span>
            </div>
            <div class="h-px bg-border"></div>
            <div class="flex justify-between">
              <span class="font-bold">Total</span>
              <span class="text-xl font-extrabold text-accent">
                {formatPrice(cart.total, selectedCountryData?.currency)}
              </span>
            </div>
          </div>

          <ReevitCheckout
            publicKey={publicKey}
            amount={cart.total}
            currency={selectedCountryData?.currency || 'GHS'}
            email={customerEmail}
            reference={`ORD-${Date.now()}`}
            metadata={{
              customer_name: customerName,
              order_items: cart.items.map((i) => i.product.id).join(','),
              // IMPORTANT: These values are required for webhook routing
              // Get your org_id and connection_id from your Reevit dashboard
              org_id: import.meta.env.VITE_REEVIT_ORG_ID || 'your-organization-id',
              connection_id: import.meta.env.VITE_REEVIT_CONNECTION_ID || 'your-connection-id',
              // payment_id is typically the order/invoice ID from your system
              payment_id: `ORD-${Date.now()}`
            }}
            paymentMethods={['card', 'mobile_money']}
            theme={{ primaryColor: '#6366f1', darkMode: true }}
            on:success={handlePaymentSuccess}
            on:error={handlePaymentError}
          >
            <button class="btn btn-primary w-full h-14 text-lg font-bold shadow-glow animate-pulse-glow">
              Pay {formatPrice(cart.total, selectedCountryData?.currency)}
            </button>
          </ReevitCheckout>

          <p class="mt-6 text-xs text-center text-muted-foreground">🔒 100% Encrypted & Secure</p>
        </div>
      </div>
    </div>
  </main>
{/if}
