// svelte+reevit/src/components/Header.svelte
<script lang="ts">
  import { ShoppingCart, Zap } from 'lucide-svelte'
  import { cart } from '$lib/cart.svelte'
</script>

<header class="sticky top-0 z-50 glass">
  <div class="container mx-auto px-6 h-16 flex items-center justify-between">
    <a href="#/" class="flex items-center gap-2 group">
      <div class="w-8 h-8 rounded-lg gradient-accent flex items-center justify-center shadow-glow">
        <Zap class="w-4 h-4 text-white" />
      </div>
      <span class="font-bold text-xl">
        Tech<span class="text-[var(--color-accent)]">Shop</span>
      </span>
    </a>

    <nav class="flex items-center gap-6">
      <a href="#/" class="text-sm font-medium text-[var(--color-muted-foreground)] hover:text-[var(--color-foreground)] transition-colors">
        Products
      </a>
      <a href="#/cart" class="relative group">
        <div class="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center transition-all group-hover:bg-white/10">
          <ShoppingCart class="w-5 h-5" />
        </div>
        {#if cart.itemCount > 0}
          <span class="absolute -top-1 -right-1 w-5 h-5 rounded-full gradient-accent text-[10px] font-bold flex items-center justify-center">
            {cart.itemCount}
          </span>
        {/if}
      </a>
    </nav>
  </div>
</header>

// nextjs-reevit/components/Header.tsx
'use client'

import Link from 'next/link'
import { HugeiconsIcon } from '@hugeicons/react'
import { ShoppingCart01Icon, User02Icon, Search01Icon } from '@hugeicons/core-free-icons'
import { useCart } from '../lib/cart'
import { Button } from './ui/button'

export function Header() {
  const { itemCount } = useCart()

  return (
    <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-backdrop-filter:bg-background/60">
      <div className="container mx-auto flex h-16 items-center justify-between px-4">
        {/* Logo */}
        <Link href="/" className="flex items-center gap-2">
          <span className="text-xl font-bold tracking-tight">REEVIT STORE</span>
        </Link>

        {/* Navigation */}
        <nav className="hidden md:flex items-center gap-8">
          <Link href="/" className="text-sm font-medium text-foreground hover:text-primary transition-colors">
            Latest Products
          </Link>
          <span className="text-sm font-medium text-muted-foreground hover:text-foreground cursor-pointer transition-colors">
            Our Collection
          </span>
          <span className="text-sm font-medium text-muted-foreground hover:text-foreground cursor-pointer transition-colors">
            Artisans
          </span>
          <span className="text-sm font-medium text-muted-foreground hover:text-foreground cursor-pointer transition-colors">
            Customer Service
          </span>
        </nav>

        {/* Right Actions */}
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="icon" className="hidden md:flex">
            <HugeiconsIcon icon={Search01Icon} className="h-5 w-5" />
          </Button>
          <Button variant="ghost" size="icon">
            <HugeiconsIcon icon={User02Icon} className="h-5 w-5" />
          </Button>
          <Link href="/cart">
            <Button variant="ghost" size="icon" className="relative">
              <HugeiconsIcon icon={ShoppingCart01Icon} className="h-5 w-5" />
              {itemCount > 0 && (
                <span className="absolute -top-1 -right-1 h-5 w-5 rounded-full bg-primary text-primary-foreground text-xs font-bold flex items-center justify-center">
                  {itemCount}
                </span>
              )}
            </Button>
          </Link>
        </div>
      </div>
    </header>
  )
}
