// svelte+reevit/src/App.svelte
<script lang="ts">
  import Header from './components/Header.svelte'
  import Home from './routes/Home.svelte'
  import Cart from './routes/Cart.svelte'
  import Checkout from './routes/Checkout.svelte'
  import PaymentStatus from './routes/PaymentStatus.svelte'

  // Simple hash-based router for demo
  let currentRoute = $state(window.location.hash.slice(1) || '/')
  
  function handleHashChange() {
    currentRoute = window.location.hash.slice(1) || '/'
  }

  $effect(() => {
    window.addEventListener('hashchange', handleHashChange)
    return () => window.removeEventListener('hashchange', handleHashChange)
  })
</script>

<div class="min-h-screen">
  <Header />
  
  {#if currentRoute === '/'}
    <Home />
  {:else if currentRoute === '/cart'}
    <Cart />
  {:else if currentRoute === '/checkout'}
    <Checkout />
  {:else if currentRoute.startsWith('/payment/')}
    <PaymentStatus paymentId={currentRoute.replace('/payment/', '')} />
  {:else}
    <Home />
  {/if}
</div>

// react+reevit/src/App.tsx
import { Routes, Route } from 'react-router-dom'
import { Toaster } from './components/ui/Toaster'
import Header from './components/Header'
import Home from './pages/Home'
import Cart from './pages/Cart'
import Checkout from './pages/Checkout'
import PaymentStatus from './pages/PaymentStatus'

export default function App() {
  return (
    <div className="min-h-screen">
      <Header />
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/cart" element={<Cart />} />
        <Route path="/checkout" element={<Checkout />} />
        <Route path="/payment/:id" element={<PaymentStatus />} />
      </Routes>
      <Toaster />
    </div>
  )
}
