// tanstack-start+reevit/src/components/ProductCard.tsx
'use client'

import { HugeiconsIcon } from '@hugeicons/react'
import { FavouriteIcon, ShoppingCart01Icon } from '@hugeicons/core-free-icons'
import { formatPrice } from '../lib/products'
import { useCart } from '../lib/cart'
import { Card, CardContent } from './ui/card'
import { Button } from './ui/button'
import { Badge } from './ui/badge'
import type { Product } from '../lib/products'

interface ProductCardProps {
  product: Product
}

export function ProductCard({ product }: ProductCardProps) {
  const { addItem } = useCart()

  return (
    <Card className="group overflow-hidden border-0 shadow-none bg-transparent p-0">
      <div className="relative aspect-square overflow-hidden rounded-t-lg bg-muted">
        <img
          src={product.image}
          alt={product.name}
          className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
        />
        {product.badge && (
          <Badge
            variant={product.badge === 'Sale' ? 'destructive' : 'secondary'}
            className="absolute top-3 left-3 font-medium"
          >
            {product.badge}
          </Badge>
        )}
        <Button
          onClick={() => addItem(product)}
          size="icon"
          className="absolute bottom-3 right-3 opacity-0 group-hover:opacity-100 transition-opacity shadow-lg"
        >
          <HugeiconsIcon icon={ShoppingCart01Icon} className="h-4 w-4" />
        </Button>
      </div>
      <CardContent className="px-4 py-4">
        <div className='flex justify-between items-center'>
          <div>
            <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1">
              {product.category}
            </p>
            <h3 className="font-semibold text-foreground mb-2 line-clamp-1">
              {product.name}
            </h3>
          </div>
          <div className="flex items-center gap-1 mb-2">
            <HugeiconsIcon icon={FavouriteIcon} className="h-3.5 w-3.5 fill-primary text-primary" />
            <span className="text-xs text-muted-foreground">{product.rating}</span>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className="font-bold text-foreground">
            {formatPrice(product.price)}
          </span>
          {product.originalPrice && (
            <span className="text-sm text-muted-foreground line-through">
              {formatPrice(product.originalPrice)}
            </span>
          )}
        </div>
      </CardContent>
    </Card>
  )
}

// vue-reevit/src/components/ProductCard.vue
<template>
  <div class="group overflow-hidden border-0 shadow-none bg-transparent p-0">
    <div class="relative aspect-square overflow-hidden rounded-t-lg bg-muted">
      <img :src="product.image" :alt="product.name" class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" />
      <button @click="cart.addItem(product)" class="absolute bottom-3 right-3 bg-primary text-primary-foreground p-2 rounded-md opacity-0 group-hover:opacity-100 transition-opacity">
        🛒
      </button>
    </div>
    <div class="px-4 py-4">
      <div class="flex justify-between items-center">
        <div>
          <p class="text-xs text-muted-foreground uppercase">{{ product.category }}</p>
          <h3 class="font-semibold">{{ product.name }}</h3>
        </div>
        <div class="flex items-center gap-1">
          ⭐
          <span class="text-xs">{{ product.rating }}</span>
        </div>
      </div>
      <div class="flex items-center gap-2 mt-2">
        <span class="font-bold">{{ formatPrice(product.price) }}</span>
        <span v-if="product.originalPrice" class="text-sm text-muted-foreground line-through">
          {{ formatPrice(product.originalPrice) }}
        </span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { formatPrice, type Product } from '@/lib/products'
import { useCartStore } from '@/stores/cart'

defineProps<{
  product: Product
}>()

const cart = useCartStore()
</script>
