// svelte+reevit/src/routes/Checkout.svelte
<script lang="ts">
  import { ArrowLeft, ShieldCheck } from 'lucide-svelte'
  import { ReevitCheckout } from '@reevit/svelte'
  import { cart } from '$lib/cart.svelte'
  import { formatPrice } from '$lib/products'

  let customerEmail = $state('')
  let customerName = $state('')
  let selectedCountry = $state('GH')
  const orderId = `ORD-${Date.now()}`

  const countries = [
    { code: 'GH', name: 'Ghana', currency: 'GHS' },
    { code: 'NG', name: 'Nigeria', currency: 'NGN' },
    { code: 'KE', name: 'Kenya', currency: 'KES' },
  ]

  const selectedCountryData = $derived(countries.find((c) => c.code === selectedCountry))
  const publicKey = import.meta.env.VITE_REEVIT_PUBLIC_KEY || 'pfk_test_demo'

  function handlePaymentSuccess(event: CustomEvent) {
    const result = event.detail
    cart.clearCart()
    window.location.hash = `/payment/${result.reference || result.id}`
  }

  function handlePaymentError(event: CustomEvent) {
    console.error('Payment failed:', event.detail)
  }
</script>

{#if cart.items.length === 0}
  <main class="container mx-auto px-6 py-24 text-center">
    <div class="text-6xl mb-6">🛒</div>
    <h1 class="text-3xl font-bold mb-4">Your cart is empty</h1>
    <p class="text-muted-foreground mb-8">Add some products before checking out</p>
    <a href="#/" class="btn btn-primary h-12 px-8 text-lg">
      <ArrowLeft class="w-5 h-5 mr-2" /> Continue Shopping
    </a>
  </main>
{:else}
  <main class="container mx-auto px-6 py-12">
    <div class="flex items-center gap-4 mb-12">
      <a href="#/cart" class="btn btn-ghost h-10 w-10 p-0">
        <ArrowLeft class="w-5 h-5" />
      </a>
      <h1 class="text-4xl font-bold">Checkout</h1>
    </div>

    <div class="grid lg:grid-cols-3 gap-12">
      <div class="lg:col-span-2 space-y-8">
        <section class="glass p-8 rounded-3xl">
          <h2 class="text-2xl font-bold mb-6">Customer Information</h2>
          <div class="grid sm:grid-cols-2 gap-6">
            <div>
              <label class="block text-sm font-bold text-muted-foreground mb-2">Full Name</label>
              <input bind:value={customerName} type="text" placeholder="John Doe" class="input" required />
            </div>
            <div>
              <label class="block text-sm font-bold text-muted-foreground mb-2">Email Address</label>
              <input bind:value={customerEmail} type="email" placeholder="john@example.com" class="input" required />
            </div>
          </div>
          <div class="mt-6">
            <label class="block text-sm font-bold text-muted-foreground mb-2">Country</label>
            <select bind:value={selectedCountry} class="input appearance-none cursor-pointer">
              {#each countries as country (country.code)}
                <option value={country.code} class="bg-background">{country.name} ({country.currency})</option>
              {/each}
            </select>
          </div>
        </section>

        <div class="glass p-6 rounded-2xl border border-accent/20 bg-accent/5">
          <div class="flex items-start gap-4">
            <div class="w-12 h-12 rounded-xl bg-accent/10 flex items-center justify-center shrink-0">
              <ShieldCheck class="w-6 h-6 text-accent" />
            </div>
            <div>
              <h3 class="text-lg font-bold mb-1">Secure Checkout</h3>
              <p class="text-sm text-muted-foreground">
                Your payment is securely processed through <span class="text-foreground font-semibold">Reevit's</span> unified payment platform.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="lg:sticky lg:top-24 h-fit">
        <div class="glass p-8 rounded-3xl">
          <h2 class="text-xl font-bold mb-6">Order Summary</h2>
          <div class="space-y-4 mb-6">
            {#each cart.items as item (item.product.id)}
              <div class="flex items-center gap-3">
                <div class="w-12 h-12 rounded-lg overflow-hidden shrink-0">
                  <img src={item.product.image} alt={item.product.name} class="w-full h-full object-cover" />
                </div>
                <div class="flex-1 min-w-0">
                  <p class="font-medium text-sm line-clamp-1">{item.product.name}</p>
                  <p class="text-xs text-muted-foreground">Qty: {item.quantity}</p>
                </div>
                <span class="font-bold text-sm">{formatPrice(item.product.price * item.quantity)}</span>
              </div>
            {/each}
          </div>
          <div class="h-px bg-border my-6"></div>
          <div class="space-y-3 mb-8">
            <div class="flex justify-between text-sm text-muted-foreground">
              <span>Subtotal</span>
              <span class="text-foreground">{formatPrice(cart.total)}</span>
            </div>
            <div class="flex justify-between text-sm text-muted-foreground">
              <span>Shipping</span>
              <span class="text-success font-bold">Free</span>
            </div>
            <div class="h-px bg-border"></div>
            <div class="flex justify-between">
              <span class="font-bold">Total</span>
              <span class="text-xl font-extrabold text-accent">
                {formatPrice(cart.total, selectedCountryData?.currency)}
              </span>
            </div>
          </div>

          <ReevitCheckout
            publicKey={publicKey}
            amount={cart.total}
            currency={selectedCountryData?.currency || 'GHS'}
            email={customerEmail}
            reference={orderId}
            metadata={{
              customer_name: customerName,
              order_items: cart.items.map((i) => i.product.id).join(','),
              // IMPORTANT: These values are required for webhook routing
              // Get your org_id and connection_id from your Reevit dashboard
              org_id: import.meta.env.VITE_REEVIT_ORG_ID || 'your-organization-id',
              connection_id: import.meta.env.VITE_REEVIT_CONNECTION_ID || 'your-connection-id',
              // payment_id is typically the order/invoice ID from your system
              payment_id: orderId
            }}
            paymentMethods={['card', 'mobile_money']}
            theme={{ primaryColor: '#6366f1', darkMode: true }}
            on:success={handlePaymentSuccess}
            on:error={handlePaymentError}
          >
            <button class="btn btn-primary w-full h-14 text-lg font-bold shadow-glow animate-pulse-glow">
              Pay {formatPrice(cart.total, selectedCountryData?.currency)}
            </button>
          </ReevitCheckout>

          <p class="mt-6 text-xs text-center text-muted-foreground">🔒 100% Encrypted & Secure</p>
        </div>
      </div>
    </div>
  </main>
{/if}

// react+reevit/src/pages/Checkout.tsx
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowLeft, ShieldCheck } from 'lucide-react'
import { ReevitCheckout } from '@reevit/react'
import { useCart } from '@/contexts/CartContext'
import { formatPrice } from '@/lib/products'
import { toast } from '@/components/ui/Toaster'

const countries = [
  { code: 'GH', name: 'Ghana', currency: 'GHS' },
  { code: 'NG', name: 'Nigeria', currency: 'NGN' },
  { code: 'KE', name: 'Kenya', currency: 'KES' },
]

export default function Checkout() {
  const navigate = useNavigate()
  const { items, total, clearCart } = useCart()
  const [customerEmail, setCustomerEmail] = useState('')
  const [customerName, setCustomerName] = useState('')
  const [selectedCountry, setSelectedCountry] = useState('GH')

  const selectedCountryData = countries.find((c) => c.code === selectedCountry)
  const publicKey = import.meta.env.VITE_REEVIT_PUBLIC_KEY || 'pfk_test_demo'
  const [orderId] = useState(() => `ORD-${Date.now()}`)

  if (items.length === 0) {
    return (
      <main className="container mx-auto px-6 py-24 text-center">
        <div className="text-6xl mb-6">🛒</div>
        <h1 className="text-3xl font-bold mb-4">Your cart is empty</h1>
        <p className="text-muted-foreground mb-8">
          Add some products before checking out
        </p>
        <Link to="/" className="btn btn-primary h-12 px-8 text-lg">
          <ArrowLeft className="w-5 h-5 mr-2" />
          Continue Shopping
        </Link>
      </main>
    )
  }

  const handlePaymentSuccess = (result: any) => {
    toast.success('Payment successful!')
    clearCart()
    navigate(`/payment/${result.reference || result.id}`)
  }

  const handlePaymentError = (error: any) => {
    toast.error(error.message || 'Payment failed')
  }

  return (
    <main className="container mx-auto px-6 py-12">
      <div className="flex items-center gap-4 mb-12">
        <Link to="/cart" className="btn btn-ghost h-10 w-10 p-0">
          <ArrowLeft className="w-5 h-5" />
        </Link>
        <h1 className="text-4xl font-bold">Checkout</h1>
      </div>

      <div className="grid lg:grid-cols-3 gap-12">
        <div className="lg:col-span-2 space-y-8">
          {/* Customer Information */}
          <section className="glass p-8 rounded-3xl">
            <h2 className="text-2xl font-bold mb-6">Customer Information</h2>
            <div className="grid sm:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-bold text-muted-foreground mb-2">
                  Full Name
                </label>
                <input
                  type="text"
                  value={customerName}
                  onChange={(e) => setCustomerName(e.target.value)}
                  placeholder="John Doe"
                  className="input"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-bold text-muted-foreground mb-2">
                  Email Address
                </label>
                <input
                  type="email"
                  value={customerEmail}
                  onChange={(e) => setCustomerEmail(e.target.value)}
                  placeholder="john@example.com"
                  className="input"
                  required
                />
              </div>
            </div>
            <div className="mt-6">
              <label className="block text-sm font-bold text-muted-foreground mb-2">
                Country
              </label>
              <select
                value={selectedCountry}
                onChange={(e) => setSelectedCountry(e.target.value)}
                className="input appearance-none cursor-pointer"
              >
                {countries.map((country) => (
                  <option key={country.code} value={country.code} className="bg-background">
                    {country.name} ({country.currency})
                  </option>
                ))}
              </select>
            </div>
          </section>

          {/* Reevit Info */}
          <div className="glass p-6 rounded-2xl border border-accent/20 bg-accent/5">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-accent/10 flex items-center justify-center shrink-0">
                <ShieldCheck className="w-6 h-6 text-accent" />
              </div>
              <div>
                <h3 className="text-lg font-bold mb-1">Secure Checkout</h3>
                <p className="text-sm text-muted-foreground">
                  Your payment is securely processed through <span className="text-foreground font-semibold">Reevit's</span> unified payment platform. We automatically route to the best provider for your transaction.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Order Summary & Checkout */}
        <div className="lg:sticky lg:top-24 h-fit">
          <div className="glass p-8 rounded-3xl">
            <h2 className="text-xl font-bold mb-6">Order Summary</h2>

            {/* Items */}
            <div className="space-y-4 mb-6">
              {items.map((item) => (
                <div key={item.product.id} className="flex items-center gap-3">
                  <div className="w-12 h-12 rounded-lg overflow-hidden shrink-0">
                    <img
                      src={item.product.image}
                      alt={item.product.name}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="font-medium text-sm line-clamp-1">{item.product.name}</p>
                    <p className="text-xs text-muted-foreground">
                      Qty: {item.quantity}
                    </p>
                  </div>
                  <span className="font-bold text-sm">
                    {formatPrice(item.product.price * item.quantity)}
                  </span>
                </div>
              ))}
            </div>

            <div className="h-px bg-border my-6" />

            {/* Totals */}
            <div className="space-y-3 mb-8">
              <div className="flex justify-between text-sm text-muted-foreground">
                <span>Subtotal</span>
                <span className="text-foreground">{formatPrice(total)}</span>
              </div>
              <div className="flex justify-between text-sm text-muted-foreground">
                <span>Shipping</span>
                <span className="text-success font-bold">Free</span>
              </div>
              <div className="h-px bg-border" />
              <div className="flex justify-between">
                <span className="font-bold">Total</span>
                <span className="text-xl font-extrabold text-accent">
                  {formatPrice(total, selectedCountryData?.currency)}
                </span>
              </div>
            </div>

            {/* Reevit Checkout Widget */}
            <ReevitCheckout
              publicKey={publicKey}
              amount={total}
              currency={selectedCountryData?.currency || 'GHS'}
              email={customerEmail}
              reference={orderId}
              metadata={{
                customer_name: customerName,
                order_items: items.map((i) => i.product.id).join(','),
                // IMPORTANT: These values are required for webhook routing
                // Get your org_id and connection_id from your Reevit dashboard
                org_id: import.meta.env.VITE_REEVIT_ORG_ID || "your-organization-id",
                connection_id: import.meta.env.VITE_REEVIT_CONNECTION_ID || "your-connection-id",
                // payment_id is typically the order/invoice ID from your system
                payment_id: orderId
              }}
              paymentMethods={['card', 'mobile_money']}
              onSuccess={handlePaymentSuccess}
              onError={handlePaymentError}
              theme={{
                primaryColor: '#6366f1',
                darkMode: true,
              }}
            >
              <button className="btn btn-primary w-full h-14 text-lg font-bold shadow-glow animate-pulse-glow">
                Pay {formatPrice(total, selectedCountryData?.currency)}
              </button>
            </ReevitCheckout>

            <p className="mt-6 text-xs text-center text-muted-foreground">
              🔒 100% Encrypted & Secure
            </p>
          </div>
        </div>
      </div>
    </main>
  )
}
